name: Build and Push Docker image to Docker Hub

on:
  push:
    branches:
      - main  # Este workflow se ejecutará cuando haya un push en la rama 'main'
  pull_request:
    branches:
      - main  # También se ejecutará cuando haya un pull request hacia la rama 'main'

jobs:
  build:
    runs-on: ubuntu-latest  # Especifica el sistema operativo a usar (en este caso Ubuntu)

    steps:
    # Paso 1: Hacer checkout del repositorio
    - name: Checkout repository
      uses: actions/checkout@v2  # Acción para clonar el repositorio

    # Paso 2: Configurar Docker Buildx
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1  # Configuración de Docker Buildx

    # Paso 3: Iniciar sesión en Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v2  # Acción para loguearse en Docker Hub
      with:
        username: ${{ secrets.DOCKER_USERNAME }}  # Nombre de usuario de Docker Hub (configurado en los secretos de GitHub)
        password: ${{ secrets.DOCKER_PASSWORD }}  # Contraseña de Docker Hub (configurada en los secretos de GitHub)

    # Paso 4: Construir la imagen Docker
    - name: Build Docker image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/react-app:latest .  # Construcción de la imagen Docker

    # Paso 5: Subir la imagen a Docker Hub
    - name: Push Docker image to Docker Hub
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/react-app:latest  # Subir la imagen construida a Docker Hub
